/*CAST FROM INTEGER TO CHARACTER VARYING*/
ALTER TABLE instructor
ALTER COLUMN "ID" TYPE VARCHAR(140);

SELECT * FROM instructor ORDER BY dept_name, salary DESC;

/*ALTER FROM CHARACTER VARYING TO INTEGER, use USING column_name::INTEGER*/
ALTER TABLE instructor
ALTER COLUMN "ID" TYPE INTEGER USING "ID"::INTEGER;

SELECT * FROM instructor ORDER BY dept_name, salary DESC;
